# Generated by Django 4.0.7 on 2023-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_item_image_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('not begun', 'not begun'), ('started', 'started'), ('over', 'over')], max_length=30),
        ),
    ]
