# Generated by Django 4.0.7 on 2023-11-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('auction', '0003_item_bidcount_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.users'),
        ),
    ]
