# Generated by Django 4.0.7 on 2023-11-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('not begun', 'not begun'), ('started', 'started'), ('over', 'over')], default='not_begun', max_length=30),
        ),
    ]
