# Generated by Django 4.0.7 on 2023-11-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('auction', '0005_alter_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.item'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
        ),
        migrations.DeleteModel(
            name='Bids_Users',
        ),
    ]
