# Generated by Django 4.0.7 on 2023-11-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_bids_item_bids_user_delete_bids_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
    ]
